include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/injection.config.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_print
    - avoid_types_as_parameter_names
    - avoid_types_on_closure_parameters
    - prefer_relative_imports
    - prefer_single_quotes
    - use_super_parameters
