name: avtonalivator
description: Bluetooth client for Avtobarmen.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Presentation
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7

  # Logic
  flutter_bluetooth_serial:
    git:
      url: https://github.com/PhloxDev/flutter_bluetooth_serial
      ref: dev
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Data
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  # DI
  get_it: ^7.6.4
  injectable: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Build runner
  build_runner: ^2.3.3
  injectable_generator: ^2.4.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0

  # Assets generators
  rename: ^2.1.1
  flutter_native_splash: ^2.2.9
  icons_launcher: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  background_image: assets/splash.jpg

icons_launcher:
  image_path: assets/icon.png
  platforms:
    android:
      enable: true
    ios:
      enable: true