name: avtonalivator
description: Bluetooth client for Avtobarmen.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_bluetooth_serial: ^0.4.0
  flutter_native_splash: ^2.2.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  flutter_switch: ^0.3.2
  dio: ^5.3.2
  easy_debounce: ^2.0.2+1
  cached_network_image: ^3.2.1
  localstore: ^1.2.3
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons
    - assets/data

flutter_icons:
  image_path: "assets/icon.png"
  android: "launcher_icon"
  ios: false
  adaptive_icon_background: "#FAD960"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter_native_splash:
  color: "#FAD960"
  image: "assets/splash.png"
